from __future__ import annotations

import secrets
import socket
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RUNTIME_DIR = ROOT / "runtime" / "farmbot-web-app"
FARMBOT_REPO_URL = "https://github.com/FarmBot/Farmbot-Web-App"
FARMBOT_BRANCH = "main"


class FarmBotStackError(RuntimeError):
    pass


def _run(command: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            cwd=str(cwd) if cwd else None,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        stdout = (exc.stdout or "").strip()
        detail = stderr or stdout or str(exc)
        raise FarmBotStackError(detail) from exc


def detect_local_host() -> str:
    candidates: list[str] = []

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
            probe.connect(("8.8.8.8", 80))
            ip_address = probe.getsockname()[0]
            if ip_address:
                candidates.append(ip_address)
    except OSError:
        pass

    try:
        for result in socket.getaddrinfo(socket.gethostname(), None, family=socket.AF_INET):
            ip_address = result[4][0]
            if ip_address:
                candidates.append(ip_address)
    except OSError:
        pass

    for ip_address in candidates:
        if ip_address.startswith("127.") or ip_address.startswith("169.254."):
            continue
        return ip_address

    return "127.0.0.1"


def _secret_hex(bytes_count: int) -> str:
    return secrets.token_hex(bytes_count)


def render_env(*, host: str, port: int, admin_password: str) -> str:
    lines = [
        "# Generated by garden-helper for local FarmBot use.",
        "# FarmBot prefers a real LAN IP here instead of localhost.",
        f"API_HOST={host}",
        f"API_PORT={port}",
        f"MQTT_HOST={host}",
        f"POSTGRES_PASSWORD={_secret_hex(24)}",
        f"DEVISE_SECRET={_secret_hex(64)}",
        f"ADMIN_PASSWORD={admin_password}",
        f"SECRET_KEY_BASE={_secret_hex(64)}",
        "RAILS_ENV=production",
        "NO_EMAILS=TRUE",
        "REDIS_URL=redis://redis:6379/0",
        f"MQTT_WS=ws://{host}:3002/ws",
        "MAX_POOL_SIZE=1",
        "MAX_REQUESTS=1000",
        "NO_CLEAN=true",
        "",
    ]
    return "\n".join(lines)


def prepare_farmbot_stack(
    *,
    runtime_dir: str | Path = DEFAULT_RUNTIME_DIR,
    host: str | None = None,
    port: int = 3000,
    repo_url: str = FARMBOT_REPO_URL,
    branch: str = FARMBOT_BRANCH,
) -> dict[str, Any]:
    runtime_path = Path(runtime_dir).resolve()
    runtime_path.parent.mkdir(parents=True, exist_ok=True)

    actions: list[str] = []
    warnings: list[str] = []

    if runtime_path.exists():
        if not (runtime_path / ".git").exists():
            raise FarmBotStackError(f"{runtime_path} exists but is not a git checkout")
        actions.append("reused_existing_repo")
        try:
            _run(["git", "fetch", "--depth", "1", "origin", branch], cwd=runtime_path)
            actions.append("fetched_remote")
        except FarmBotStackError as exc:
            warnings.append(f"git fetch skipped: {exc}")
    else:
        _run(["git", "clone", "--depth", "1", "--branch", branch, repo_url, str(runtime_path)])
        actions.append("cloned_repo")

    host_value = host or detect_local_host()
    if host_value.startswith("127."):
        warnings.append(
            "detected loopback host; FarmBot prefers a real LAN IPv4 address. "
            "Override with --host if MQTT auth fails."
        )

    admin_password = secrets.token_urlsafe(18)
    env_path = runtime_path / ".env"
    env_path.write_text(
        render_env(host=host_value, port=port, admin_password=admin_password),
        encoding="utf-8",
    )
    actions.append("wrote_env")

    for relative_path in (
        "docker_volumes",
        "docker_volumes/db",
        "docker_volumes/redis/data",
        "docker_volumes/redis/conf",
        "docker_volumes/rabbit",
        "docker_volumes/bundle_cache",
    ):
        (runtime_path / relative_path).mkdir(parents=True, exist_ok=True)

    return {
        "runtime_dir": str(runtime_path),
        "repo_url": repo_url,
        "branch": branch,
        "api_host": host_value,
        "api_port": port,
        "env_path": str(env_path),
        "docker_compose_file": str(runtime_path / "docker-compose.yml"),
        "compose_up_command": f'docker compose up --build',
        "admin_password": admin_password,
        "actions": actions,
        "warnings": warnings,
    }
